"""Live-API integration test for safety_reports/weekly_send.py.

Per Op Stds v11 §30 (SDK-vs-Live Integration Test Discipline) — every
typed-SDK write path needs a parallel integration test against a real
Smartsheet sandbox row. This file exercises:

  - smartsheet_client.add_rows / get_row / update_rows against the live
    WPR_Pending_Review sheet.
  - graph_client.send_mail against the live sandbox mailbox.
  - weekly_send.send_one_row end-to-end (full 7-stage pipeline).

Default `pytest -q` SKIPS this file (per pyproject.toml addopts:
-m 'not integration'). Run with `pytest -m integration`. Requires:

  - ITS_SMARTSHEET_TOKEN in macOS Keychain.
  - Graph credentials (client_id / client_secret / tenant_id) in Keychain.

Without either, the module-level fixture skips the file cleanly.

Sandbox isolation:
  - Seeded row uses Job="_int_weekly_send_sandbox" + Week=1970-01-05 so
    it can't collide with real production rows.
  - Recipient is seths@evergreenmirror.com — operator's mirror inbox.
  - Try/finally cleanup deletes the row regardless of outcome.

Cost: one Graph send (~negligible) per run. Manual inbox cleanup may
be needed after first few runs (see docs/tech_debt.md for the
automated-mailbox-cleanup tech-debt entry).

NOT run in CI: GitHub Actions has neither keychain secret.
"""
from __future__ import annotations

import json
from datetime import date

import pytest

from safety_reports import weekly_send
from shared import keychain, sheet_ids, smartsheet_client

pytestmark = pytest.mark.integration

SANDBOX_JOB = "_int_weekly_send_sandbox"
SANDBOX_WEEK = date(1970, 1, 5)  # arbitrary far-past Monday, collision-free.
SANDBOX_RECIPIENT = "seths@evergreenmirror.com"


@pytest.fixture(scope="module")
def _smartsheet_token() -> str:
    try:
        token = keychain.get_secret("ITS_SMARTSHEET_TOKEN")
    except Exception as e:  # noqa: BLE001
        pytest.skip(f"ITS_SMARTSHEET_TOKEN unavailable: {e!r}")
    if not token:
        pytest.skip("ITS_SMARTSHEET_TOKEN returned empty")
    return token


@pytest.fixture(scope="module")
def _graph_credentials() -> None:
    """Skip if Graph credentials aren't reachable; no return value needed."""
    try:
        # Minimal probe — token acquisition exercises the same MSAL path
        # send_mail would use. Raises GraphAuthError on missing/wrong creds.
        from shared import graph_client

        graph_client._get_token()
    except Exception as e:  # noqa: BLE001
        pytest.skip(f"Graph credentials unavailable: {e!r}")


def test_weekly_send_end_to_end_sends_and_marks_row(
    _smartsheet_token: str,
    _graph_credentials: None,
) -> None:
    """End-to-end: seed approved sandbox row, send, assert SENT, cleanup."""
    sandbox_row_id: int | None = None
    try:
        # 1. Seed an approved-PENDING WPR row with Recipient = seths mirror.
        body = (
            "[ITS-SMOKE-TEST] This is the weekly_send integration test "
            "fixture. Safe to delete from the mailbox after receipt.\n\n"
            "Generated by tests/test_weekly_send_integration.py."
        )
        new_ids = smartsheet_client.add_rows(
            sheet_ids.SHEET_WPR_PENDING_REVIEW,
            [
                {
                    "Customer": "Forefront",
                    "Job": SANDBOX_JOB,
                    "Week": SANDBOX_WEEK.isoformat(),
                    "Draft Body": body,
                    "Recipients": json.dumps([SANDBOX_RECIPIENT]),
                    "Approved for Send": True,
                    "Send Status": weekly_send.STATUS_PENDING,
                    "Late Send": False,
                    "Notes": "[ITS-SMOKE-TEST] integration test seed",
                }
            ],
        )
        assert len(new_ids) == 1
        sandbox_row_id = new_ids[0]

        # 2. Invoke send_one_row.
        result = weekly_send.send_one_row(sandbox_row_id)

        # 3. Assert SENT outcome.
        assert result.status == "sent", (
            f"expected status=sent, got {result.status!r} error={result.error!r}"
        )
        assert result.row_id == sandbox_row_id
        assert result.project_name == SANDBOX_JOB

        # 4. Verify the row is marked SENT in Smartsheet.
        fetched = smartsheet_client.get_row(
            sheet_ids.SHEET_WPR_PENDING_REVIEW, sandbox_row_id
        )
        assert fetched["Send Status"] == weekly_send.STATUS_SENT
        assert fetched["Sent At"]  # not empty
        assert "sent=" in (fetched.get("Notes") or "")
    finally:
        # 5. Cleanup — delete the row regardless of outcome.
        if sandbox_row_id is not None:
            try:
                smartsheet_client.delete_rows(
                    sheet_ids.SHEET_WPR_PENDING_REVIEW, [sandbox_row_id]
                )
            except Exception:  # noqa: BLE001 — cleanup best-effort
                pass
