"""Insert/refresh a troubleshooting-tree cross-link header in each referenced runbook.

The tree (`docs/troubleshooting/tree.yaml`) links FORWARD to runbooks (a node's `runbook:`).
This adds the REVERSE link: a bounded, marker-delimited block near the top of each runbook the
tree references, naming the tree node(s) it resolves + the daemon(s) involved, and linking the
guide + daemon reference. Idempotent (re-run to refresh as the tree grows); the block sits
between HTML-comment markers so hand-edited prose is untouched.

Usage:
    python -m scripts.build_runbook_xrefs            # write/refresh the blocks
    python -m scripts.build_runbook_xrefs --check    # CI: exit 1 if any block is missing/stale

Network-free, deterministic (tree order). A runbook the tree does NOT reference is left alone.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from troubleshooting.loader import load_tree

REPO_ROOT = Path(__file__).resolve().parent.parent
RUNBOOK_DIR = REPO_ROOT / "docs" / "runbooks"

BEGIN = "<!-- BEGIN TREE-XREF (generated by scripts/build_runbook_xrefs.py — do not edit inside) -->"
END = "<!-- END TREE-XREF -->"
_BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)


def _runbook_index() -> dict[str, dict[str, list[str]]]:
    """runbook filename → {'nodes': [Workflow → Step → symptom], 'daemons': [labels]}."""
    tree = load_tree()
    idx: dict[str, dict[str, list[str]]] = {}
    for wf in tree.workflows:
        for st in wf.steps:
            for fm in st.failure_modes:
                if not fm.runbook:
                    continue
                name = fm.runbook.split("#", 1)[0].split("/")[-1]
                entry = idx.setdefault(name, {"nodes": [], "daemons": []})
                node = f"{wf.title} → {st.title} → “{fm.symptom}”"
                if node not in entry["nodes"]:
                    entry["nodes"].append(node)
                if st.what_happens.daemon and st.what_happens.daemon not in entry["daemons"]:
                    entry["daemons"].append(st.what_happens.daemon)
    return idx


def _render_block(info: dict[str, list[str]]) -> str:
    lines = [BEGIN]
    lines.append(
        "> **In the troubleshooting tree** "
        "([printable guide](../troubleshooting/troubleshooting_guide.md) · "
        "dashboard `/troubleshoot`). This runbook resolves:"
    )
    for node in info["nodes"]:
        lines.append(f">   - {node}")
    if info["daemons"]:
        dae = ", ".join(f"`{d}`" for d in info["daemons"])
        lines.append(
            f"> Daemon(s): {dae} — see the [daemon reference](../references/daemon_reference.md)."
        )
    lines.append(END)
    return "\n".join(lines)


def _apply(text: str, block: str) -> str:
    """Insert `block` after the first H1 (or refresh it in place if already present)."""
    if _BLOCK_RE.search(text):
        return _BLOCK_RE.sub(block + "\n", text, count=1)
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    inserted = False
    for line in lines:
        out.append(line)
        if not inserted and line.lstrip().startswith("# "):
            out.append("\n" + block + "\n")
            inserted = True
    if not inserted:  # no H1 — prepend
        return block + "\n\n" + text
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build runbook → tree cross-link headers")
    ap.add_argument("--check", action="store_true", help="exit 1 if any block is missing/stale")
    args = ap.parse_args(argv)
    idx = _runbook_index()
    stale: list[str] = []
    written = 0
    for name in sorted(idx):
        path = RUNBOOK_DIR / name
        if not path.is_file():
            continue  # dead links are caught by tests/test_troubleshooting_tree.py
        current = path.read_text(encoding="utf-8")
        desired = _apply(current, _render_block(idx[name]))
        if current == desired:
            continue
        if args.check:
            stale.append(name)
        else:
            path.write_text(desired, encoding="utf-8")
            written += 1
    if args.check:
        if stale:
            print(
                f"{len(stale)} runbook xref block(s) missing/stale: {stale} — run "
                "`python -m scripts.build_runbook_xrefs`",
                file=sys.stderr,
            )
            return 1
        print(f"all {len(idx)} referenced-runbook xref blocks are current.")
        return 0
    print(f"wrote/refreshed {written} runbook xref block(s) ({len(idx)} referenced).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
